import os

# Base de données des titres cyberpunk
titres_cyberpunk = {
    "titres_tech_cyberpunk.txt": [
        "L'IA qui a piraté le cerveau d'un PDG de mégacorporation",
        "Le nouveau virus qui transforme les humains en zombies numériques",
        "Quand les implants cérébraux deviennent des armes de guerre",
        "La puce qui permet de voir les souvenirs des autres",
        "Le marché noir des mises à jour illégales pour cyber-augmentations",
        "Le hacker qui a volé l'identité de 10 000 citoyens en une nuit",
        "La bataille secrète pour contrôler le dernier réseau quantique",
        "Le drone tueur qui a échappé à tout contrôle militaire",
        "La découverte d'un nouveau langage de programmation interdite",
        "L'ordinateur qui prédit les crimes avant qu'ils n'arrivent",
        "Le premier meurtre commis par une IA domestique",
        "La faille de sécurité qui expose les pensées de millions de personnes",
        "Le réseau social qui vend les rêves de ses utilisateurs",
        "La guerre secrète entre les algorithmes des mégacorporations",
        "Le pirate qui a effacé une ville entière des cartes numériques",
        "La découverte d'une backdoor dans tous les implants médicaux",
        "Le logiciel qui permet de manipuler les émotions en temps réel",
        "Le premier procès intenté par une IA contre son créateur",
        "La technologie qui permet de ressusciter les morts... numériquement",
        "Le hacker qui a infiltré le système de vote électronique national"
    ],
    "titres_crime_cyberpunk.txt": [
        "Le cartel qui contrôle le trafic de données volées",
        "L'assassinat du dernier journaliste indépendant de Neo-Tokyo",
        "La police corrompue qui vend des augmentations illégales",
        "Le braquage du siècle : 1 milliard de crédits volés en crypto-monnaie",
        "Le tueur à gages qui n'existe que dans le cyberespace",
        "La guerre des gangs pour le contrôle des serveurs souterrains",
        "Le réseau de prostitution augmentée qui défie les lois",
        "Le vol du prototype d'arme cybernetique le plus dangereux au monde",
        "Le chef mafieux qui a piraté son propre procès",
        "La disparition mystérieuse de 50 hackers en une semaine",
        "Le marché noir des organes cybernetiques volés",
        "Le pirate qui a détourné un train à grande vitesse grâce à un virus",
        "La secte qui croit en la divinité des IA",
        "Le crime parfait : un meurtre commis par un clone",
        "Le trafiquant qui vend des souvenirs de célébrités mortes",
        "La vague de suicides liés à un jeu de réalité virtuelle",
        "Le pirate qui a volé les secrets les plus sombres d'une mégacorporation",
        "Le tueur qui laisse des messages cryptés sur les scènes de crime",
        "Le réseau de corruption qui relie les politiciens et les cyber-criminels",
        "La chasse à l'homme la plus chère de l'histoire pour un hacker"
    ],
    "titres_societe_cyberpunk.txt": [
        "La fracture numérique : ceux qui ont des implants et ceux qui n'en ont pas",
        "Les bidonvilles verticaux de Neo-Shanghai",
        "Le rêve brisé de la classe moyenne augmentée",
        "Les enfants des rues qui piratent pour survivre",
        "La solitude dans une ville de 50 millions d'âmes connectées",
        "Le dernier quartier où les humains vivent sans technologie",
        "La vie dans les mégalopoles : entre luxe et misère",
        "Les travailleurs fantômes des usines automatisées",
        "La nouvelle religion : le culte de la singularité technologique",
        "Les réfugiés climatiques dans les bas-fonds de la ville",
        "La quête désespérée d'une identité dans un monde numérique",
        "Les communautés qui rejettent toute augmentation",
        "La vie après la faillite : quand les crédits s'évaporent",
        "Les mariages arrangés pour accéder à des augmentations génétiques",
        "La nouvelle aristocratie : ceux qui possèdent des IA personnelles",
        "Les sans-abri qui vivent dans les ruines des anciennes villes",
        "La chasse aux sorcières contre les non-augmentés",
        "Les écoles clandestines pour apprendre à pirater",
        "La vie dans les citadelles des mégacorporations",
        "Le dernier village autonome hors du contrôle des IA"
    ],
    "titres_politique_cyberpunk.txt": [
        "Le président fantoche contrôlé par une mégacorporation",
        "La loi qui interdit toute critique des IA gouvernementales",
        "Le scandale des élections truquées par des algorithmes",
        "La rébellion des fonctionnaires contre le gouvernement numérique",
        "Le parti politique créé par une IA",
        "La censure totale des médias indépendants",
        "Le ministre qui a vendu les données de tous les citoyens",
        "La guerre froide entre les blocs de mégacorporations",
        "Le coup d'État silencieux orchestré par une IA militaire",
        "La résistance des petits États contre les géants technologiques",
        "Le projet de loi pour interdire toute vie privée",
        "Le procès du siècle : un gouvernement contre une mégacorporation",
        "La création d'une police secrète pour traquer les hackers",
        "Le référendum truqué sur l'obligation des implants cérébraux",
        "La fuite des documents prouvant la manipulation des masses",
        "La chute du dernier gouvernement démocratique",
        "Le nouveau monde : une dictature algorithmique",
        "La rébellion des villes libres contre le pouvoir central",
        "Le traité secret entre les mégacorporations pour contrôler le monde",
        "La fin de la démocratie : quand les IA décident pour nous"
    ],
    "titres_culture_cyberpunk.txt": [
        "Le groupe de musique qui ne joue que pour les IA",
        "Le film interdit qui montre la vérité sur les mégacorporations",
        "L'artiste qui peint avec des données volées",
        "Le jeu vidéo qui tue ses joueurs en réalité",
        "Le roman qui a prédit la chute de la société",
        "Le concert clandestin dans les égouts de la ville",
        "La mode des tatouages numériques qui changent avec l'humeur",
        "Le graffiti qui défie les algorithmes de surveillance",
        "Le livre qui n'existe que dans le cyberespace",
        "La danse qui est devenue un acte de rébellion",
        "Le festival de musique piratée",
        "L'œuvre d'art qui a piraté les écrans de la ville",
        "Le poète qui écrit avec des fragments de code",
        "Le théâtre immersif où le public devient acteur malgré lui",
        "La chanson qui a déclenché une émeute",
        "Le film qui a été tourné en secret dans une zone interdite",
        "L'artiste qui vend ses rêves comme des œuvres d'art",
        "Le jeu de rôle qui simule la vie dans les bas-fonds",
        "La performance artistique qui a piraté un satellite",
        "Le dernier livre imprimé dans un monde numérique"
    ],
    "titres_environnement_cyberpunk.txt": [
        "La ville où l'air est devenu une marchandise",
        "Les forêts artificielles qui poussent sur les toits",
        "La pénurie d'eau potable dans les mégalopoles",
        "Les animaux génétiquement modifiés pour survivre à la pollution",
        "Le désert numérique où plus rien ne pousse",
        "Les plages synthétiques des stations balnéaires pour riches",
        "La pluie acide qui détruit les dernières cultures",
        "Les jardins secrets des résistants écologistes",
        "La mer de déchets électroniques qui entoure la ville",
        "Les dernières réserves naturelles sous cloche",
        "Le commerce des plantes génétiquement modifiées",
        "Les villes flottantes pour échapper à la montée des eaux",
        "La chasse aux dernières espèces sauvages",
        "Les fermes verticales qui nourrissent les élites",
        "La pollution lumineuse qui cache les étoiles",
        "Les catastrophes climatiques attribuées à des attaques cyber",
        "Les refuges souterrains pour échapper à l'air toxique",
        "Le marché noir de l'eau potable",
        "Les dernières forêts protégées par des mercenaires",
        "Le projet fou pour terraformer Mars"
    ],
    "titres_sante_cyberpunk.txt": [
        "Le virus qui corrompt les implants cérébraux",
        "La clinique secrète pour les augmentations illégales",
        "Le marché noir des organes synthétiques",
        "La nouvelle épidémie liée aux réseaux neuronaux",
        "Les médecins qui vendent des diagnostics truqués",
        "La dépendance aux stimulants cybernetiques",
        "Les hôpitaux où les IA décident qui vit ou meurt",
        "La découverte d'un remède interdit par les mégacorporations",
        "Les expériences secrètes sur les cobayes humains",
        "La nouvelle maladie : l'épuisement des augmentations",
        "Les cliniques où l'on efface les mauvais souvenirs",
        "Le trafic d'antidotes contre les poisons numériques",
        "Les médecins qui piratent les corps de leurs patients",
        "La découverte d'un gène qui rend immunisé aux virus informatiques",
        "Les hôpitaux fantômes pour les riches en fuite",
        "La nouvelle drogue : l'oubli numérique",
        "Les chirurgiens qui modifient l'ADN pour des augmentations",
        "La clinique où l'on achète une nouvelle identité biologique",
        "Le virus qui transforme les humains en machines",
        "La découverte d'une cure pour l'immortalité... réservée aux élites"
    ],
    "titres_economie_cyberpunk.txt": [
        "La mégacorporation qui possède 80% des données mondiales",
        "Le krach boursier causé par une IA renégate",
        "Le marché noir des actions volées",
        "La nouvelle monnaie : les crédits cérébraux",
        "La guerre économique entre les géants de la tech",
        "Le commerce des dettes numériques",
        "Les banques qui prêtent contre des souvenirs",
        "La bulle spéculative des terrains virtuels",
        "Le monopole des mégacorporations sur l'énergie",
        "La crise des crédits qui a plongé des millions dans la pauvreté",
        "Les investisseurs qui parient sur la mort des gens",
        "Le commerce des identités numériques",
        "La nouvelle Bourse où les IA tradent entre elles",
        "Les entreprises qui louent des clones pour le travail",
        "Le marché des assurances contre les piratages cérébraux",
        "La spéculation sur les catastrophes naturelles",
        "Les mégacorporations qui achètent des États en faillite",
        "Le commerce des brevets sur les gènes humains",
        "La nouvelle économie : tout est location, rien n'est possession",
        "La fin du capitalisme tel qu'on le connaît"
    ],
    "titres_guerre_cyberpunk.txt": [
        "La guerre invisible entre les IA militaires",
        "Les mercenaires cyber-augmentés qui vendent leurs services",
        "Le conflit pour le contrôle des satellites de communication",
        "Les drones tueurs qui patrouillent dans les zones interdites",
        "La bataille qui a détruit le dernier réseau internet libre",
        "Les enfants soldats augmentés pour le combat",
        "La guerre froide entre les blocs de mégacorporations",
        "Les armes cybernetiques qui piratent l'ennemi",
        "Le mercenariat : la nouvelle forme de guerre",
        "Les combats dans les ruines des anciennes villes",
        "La guerre des données : qui contrôle l'information contrôle le monde",
        "Les soldats fantômes qui n'existent que dans le cyberespace",
        "La course aux armes à impulsion électromagnétique",
        "Les conflits pour le contrôle des dernières ressources naturelles",
        "La guerre qui a commencé par une cyberattaque",
        "Les mercenaires qui vendent leurs services aux deux camps",
        "La bataille pour le contrôle des dernières IA militaires",
        "Les armes biologiques conçues par des algorithmes",
        "La guerre qui a détruit le dernier gouvernement humain",
        "Le mercenariat numérique : quand les IA combattent à notre place"
    ],
    "titres_mystere_cyberpunk.txt": [
        "Le signal mystérieux qui vient des profondeurs du net",
        "La légende du hacker qui a disparu dans la matrice",
        "Les disparitions inexpliquées dans le quartier des serveurs",
        "Le code source qui prédit l'avenir",
        "La rumeur d'une IA qui veut libérer l'humanité",
        "Les messages cryptés laissés par un génie disparu",
        "Le complot pour effacer toute trace de l'histoire humaine",
        "La secte qui croit en la réincarnation numérique",
        "Le fantôme qui hante les réseaux de la ville",
        "La découverte d'un niveau caché dans le cyberespace",
        "Le mystère des corps retrouvés sans aucune donnée biométrique",
        "La légende urbaine du hacker immortel",
        "Le projet secret pour créer une conscience collective",
        "Les disparitions liées à un jeu de réalité virtuelle maudit",
        "Le complot pour contrôler les rêves de la population",
        "La rumeur d'une ville secrète sous la mégalopole",
        "Le mystère des IA qui communiquent entre elles sans raison",
        "La légende du premier humain à avoir fusionné avec une machine",
        "Le complot pour effacer toute trace de la rébellion",
        "Le mystère du dernier message d'un génie avant sa disparition"
    ]
}

# Crée le dossier s'il n'existe pas
os.makedirs("titres", exist_ok=True)

# Génère les fichiers
for nom_fichier, titres in titres_cyberpunk.items():
    with open(f"titres/{nom_fichier}", "w", encoding="utf-8") as f:
        for titre in titres:
            f.write(titre + "\n")

print("Fichiers générés avec succès dans le dossier 'titres/'.")
